In [1]:
import tensorflow as tf

In [2]:
tf.set_random_seed(777)

In [3]:
# X and Y data
# x_train = [1,2,3]
# y_train = [1,2,3]
X = tf.placeholder(tf.float32, shape = [None])
Y = tf.placeholder(tf.float32, shape = [None])

In [4]:
# try to find valaues for w and b to compute y_data = x_data * w + b

# Variable -> trainable 
W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [5]:
c = tf.random_normal([4,3])   # dimention

In [6]:
sess = tf.Session()
sess.run(c)

array([[ 0.93376452, -0.45112884, -0.56874341],
       [-0.48966673, -1.30393291, -0.78513855],
       [ 0.19922702, -0.12443238, -0.36293381],
       [ 0.5557369 , -1.08270359, -0.67749578]], dtype=float32)

In [7]:
hypothesis = X * W + b

In [8]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [9]:
t = [[1.,2.,3.,4.], [2.,3.,4.,5.]]
sess.run(tf.reduce_mean(t))

3.0

In [10]:
# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=.01)
train = optimizer.minimize(cost)

In [11]:
# launch the graph in a session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [12]:
# fit the line
for step in range(2001):
    cost_val, W_val, b_val, _ = \
    sess.run([cost, W, b, train], feed_dict = {X:[1,2,3,4,5], Y : [2.1,3.1,4.1, 5.1, 6.1]})
    
    if step % 20 == 0:
        print(step, cost_val, W_val, b_val)

0 1.59922 [ 0.88459384] [ 0.4831478]
20 0.0472552 [ 1.13940609] [ 0.59203142]
40 0.0412407 [ 1.13139307] [ 0.62560815]
60 0.0360158 [ 1.12279296] [ 0.65667796]
80 0.0314529 [ 1.11475122] [ 0.68571156]
100 0.027468 [ 1.10723615] [ 0.71284366]
120 0.023988 [ 1.10021317] [ 0.73819876]
140 0.020949 [ 1.09365022] [ 0.76189327]
160 0.0182949 [ 1.0875169] [ 0.7840361]
180 0.0159771 [ 1.08178544] [ 0.80472869]
200 0.0139529 [ 1.07642925] [ 0.82406616]
220 0.0121852 [ 1.07142389] [ 0.84213716]
240 0.0106414 [ 1.06674623] [ 0.85902476]
260 0.00929321 [ 1.06237507] [ 0.87480658]
280 0.00811585 [ 1.05829] [ 0.88955456]
300 0.00708763 [ 1.05447257] [ 0.90333676]
320 0.00618968 [ 1.05090499] [ 0.91621643]
340 0.00540545 [ 1.04757118] [ 0.92825282]
360 0.00472064 [ 1.04445577] [ 0.93950075]
380 0.00412256 [ 1.04154432] [ 0.95001197]
400 0.00360026 [ 1.03882337] [ 0.95983493]
420 0.00314413 [ 1.03628087] [ 0.96901447]
440 0.00274579 [ 1.03390491] [ 0.97759277]
460 0.00239792 [ 1.03168428] [ 0.98560935

In [14]:
# testing our model
sess.run(hypothesis, feed_dict={X:[5]})

array([ 6.10023975], dtype=float32)

In [15]:
sess.run(hypothesis, feed_dict={X:[2.5]})

array([ 3.59980869], dtype=float32)

In [16]:
sess.run(hypothesis, feed_dict={X:[1.5, 3.5]})

array([ 2.59963608,  4.59998131], dtype=float32)