In [30]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

In [31]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
xy

array([[  73.,   80.,   75.,  152.],
       [  93.,   88.,   93.,  185.],
       [  89.,   91.,   90.,  180.],
       [  96.,   98.,  100.,  196.],
       [  73.,   66.,   70.,  142.],
       [  53.,   46.,   55.,  101.],
       [  69.,   74.,   77.,  149.],
       [  47.,   56.,   60.,  115.],
       [  87.,   79.,   90.,  175.],
       [  79.,   70.,   88.,  164.],
       [  69.,   70.,   73.,  141.],
       [  70.,   65.,   74.,  141.],
       [  93.,   95.,   91.,  184.],
       [  79.,   80.,   73.,  152.],
       [  70.,   73.,   78.,  148.],
       [  93.,   89.,   96.,  192.],
       [  78.,   75.,   68.,  147.],
       [  81.,   90.,   93.,  183.],
       [  88.,   92.,   86.,  177.],
       [  78.,   83.,   77.,  159.],
       [  82.,   86.,   90.,  177.],
       [  86.,   82.,   89.,  175.],
       [  78.,   83.,   85.,  175.],
       [  76.,   83.,   71.,  149.],
       [  96.,   93.,   95.,  192.]], dtype=float32)

In [41]:
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

In [33]:
x_data.shape

(25, 3)

In [42]:
y_data.shape

(25, 1)

In [35]:
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]))
b = tf.Variable(tf.random_normal([1]))

In [36]:
hypothesis = tf.matmul(X, W) + b

In [37]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [38]:
optimizer = tf.train.GradientDescentOptimizer(1e-5)
train = optimizer.minimize(cost)

In [39]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [43]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  9005.32 
Prediction:
 [[ 57.67266464]
 [ 82.11399078]
 [ 74.29329681]
 [ 83.27143097]
 [ 63.47494125]
 [ 51.17467117]
 [ 61.66321182]
 [ 44.57778549]
 [ 82.19702148]
 [ 81.97789764]
 [ 60.79123306]
 [ 66.24702454]
 [ 74.78575897]
 [ 59.5628891 ]
 [ 64.0557785 ]
 [ 84.29957581]
 [ 57.82995605]
 [ 72.86673737]
 [ 68.94934082]
 [ 60.5576973 ]
 [ 73.62153625]
 [ 78.27283478]
 [ 68.42807007]
 [ 53.36897278]
 [ 82.18146515]]
10 Cost:  28.7675 
Prediction:
 [[ 146.16386414]
 [ 188.43200684]
 [ 179.07136536]
 [ 197.37712097]
 [ 144.55436707]
 [ 110.9378891 ]
 [ 147.07827759]
 [ 107.90467834]
 [ 181.5426178 ]
 [ 173.98013306]
 [ 143.07798767]
 [ 147.36360168]
 [ 183.04098511]
 [ 149.55995178]
 [ 149.85684204]
 [ 192.18574524]
 [ 143.53462219]
 [ 175.37896729]
 [ 172.16230774]
 [ 152.91203308]
 [ 173.7804718 ]
 [ 178.01052856]
 [ 163.92674255]
 [ 142.60110474]
 [ 192.37675476]]
20 Cost:  28.1757 
Prediction:
 [[ 146.79711914]
 [ 189.15287781]
 [ 179.80284119]
 [ 198.16827393]
 [ 145.098

In [45]:
sess.run(hypothesis, feed_dict = {X : [[100,70,101]]})

array([[ 200.42485046]], dtype=float32)