In [24]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility
import numpy as np

In [22]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [5]:
X = tf.placeholder(tf.float32, [None, 4])
Y = tf.placeholder(tf.float32, [None, 3])

nb_classes = 3
W = tf.Variable(tf.random_normal([4,nb_classes]))
b = tf.Variable(tf.random_normal([nb_classes]))

In [7]:
# tf.nn.softmax computes softmax activations
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)

In [61]:
# cross entropy cost function

# y is one hot encoding in this example
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(.1).minimize(cost)

In [62]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    arr = np.array(y_data)
    for step in range(2001):
        c, h, _ = \
        sess.run([cost, hypothesis, optimizer], feed_dict={X:x_data, Y:y_data})
        
        if step % 200 == 0:
            print(step, c,h)
#             print(tf.argmax(h, axis= 1).eval())

0 6.92611 [[  8.86592150e-01   3.43270153e-02   7.90807605e-02]
 [  9.98566568e-01   1.40765321e-03   2.58165383e-05]
 [  9.99217391e-01   7.24076002e-04   5.84350964e-05]
 [  9.99973416e-01   2.64343635e-05   1.03929260e-07]
 [  2.97135264e-01   1.15318799e-05   7.02853143e-01]
 [  9.98844862e-01   2.92846798e-05   1.12585758e-03]
 [  9.16804612e-01   6.30331351e-06   8.31890702e-02]
 [  8.84285867e-01   1.08126017e-06   1.15713038e-01]]
200 0.600502 [[  3.99865247e-02   6.63598254e-02   8.93653631e-01]
 [  1.03263259e-01   2.89282858e-01   6.07453883e-01]
 [  9.39009420e-04   1.91488251e-01   8.07572663e-01]
 [  1.70537014e-03   4.47234392e-01   5.51060200e-01]
 [  8.50968182e-01   8.89058560e-02   6.01259954e-02]
 [  4.42171961e-01   5.46867549e-01   1.09605053e-02]
 [  9.05767202e-01   8.74191001e-02   6.81374408e-03]
 [  9.49326396e-01   4.91243340e-02   1.54924055e-03]]
400 0.472958 [[  6.08778000e-03   2.82950979e-02   9.65617180e-01]
 [  3.78540456e-02   1.77253917e-01   7.8489