In [4]:
import tensorflow as tf
import pprint
tf.set_random_seed(777)

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [5]:
t = tf.constant([1,2,3,4])  # rank 1
tf.shape(t).eval()
# rank indicates dimentionality

array([4], dtype=int32)

In [7]:
t = tf.constant([[1,2],    # rank 2
               [3,4]])
tf.shape(t).eval()

array([2, 2], dtype=int32)

In [9]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4], dtype=int32)

In [ ]:
# axis 
[ # axis = 0
    [  # axis = 1
        [  # axis = 2
            [1,2,3,4],  # axis = 3 or -1
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]



# matmul vs multiply

In [14]:
matrix1 = tf.constant([[3,3]])
matrix2 = tf.constant([[2],[2]])
tf.matmul(matrix1, matrix2).eval()  # dot product

array([[12]], dtype=int32)

In [17]:
(matrix1*matrix2).eval()    # element-wise multiplication

array([[6, 6],
       [6, 6]], dtype=int32)

# Broadcasting

In [20]:
matrix1 = tf.constant([[3,3]])
matrix2 = tf.constant([[2],[2]])
(matrix1 + matrix2).eval()

array([[5, 5],
       [5, 5]], dtype=int32)

In [21]:
matrix1 = tf.constant([[3,3]])
matrix2 = tf.constant([[2, 2]])
(matrix1 + matrix2).eval()

array([[5, 5]], dtype=int32)

# Reduce Mean/Sum

In [22]:
tf.reduce_mean([1,2], axis = 0).eval() # integer

1

In [23]:
x = [[1.,2.], 
    [3.,4.]]
tf.reduce_mean(x).eval()

2.5

In [24]:
tf.reduce_mean(x, axis=0).eval()

array([ 2.,  3.], dtype=float32)

In [25]:
tf.reduce_mean(x, axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [26]:
tf.reduce_mean(x, axis=-1).eval()

array([ 1.5,  3.5], dtype=float32)

In [27]:
tf.reduce_sum(x).eval()

10.0

In [28]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [29]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

# Argmax

In [31]:
x = [[0,1,2],
    [2,1,0]]
tf.argmax(x, axis=0).eval() # return indices

array([1, 0, 0])

In [32]:
tf.argmax(x, axis=1).eval()

array([2, 0])

In [33]:
tf.argmax(x, axis=-1).eval()

array([2, 0])

# Reshape

In [34]:
t = tf.constant([[[0, 1, 2], 
                 [3, 4, 5]],
              
                 [[6, 7, 8], 
                 [9, 10, 11]]])
tf.shape(t).eval()

array([2, 2, 3], dtype=int32)

In [35]:
tf.reshape(t, shape = [-1, 3]).eval() # -1, 3 이렇게 두개가 들어 감으로 2차원으로 바꿈
# 3 col 하고 나머지 알아서 처리해라는 뜻

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)

In [36]:
tf.reshape(t, shape = [-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]], dtype=int32)

# squeeze

In [8]:
tf.squeeze([[0],[1],[2]]).eval()

array([0, 1, 2], dtype=int32)

# expand

In [9]:
tf.expand_dims([0,1,2],1).eval()

array([[0],
       [1],
       [2]], dtype=int32)

# one hot encoding

In [17]:
t = tf.one_hot([[0],[1],[2],[3],[0]], depth=4).eval()
t

array([[[ 1.,  0.,  0.,  0.]],

       [[ 0.,  1.,  0.,  0.]],

       [[ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  0.,  1.]],

       [[ 1.,  0.,  0.,  0.]]], dtype=float32)

In [19]:
tf.reshape(t, shape=[-1,4]).eval()

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.]], dtype=float32)

# casting

In [21]:
tf.cast([1,.8,2.2,5.4,68.5], tf.int32).eval()

array([ 1,  0,  2,  5, 68], dtype=int32)

In [23]:
tf.cast([True, False, 1--1, 0==1], tf.int32).eval()

array([1, 0, 2, 0], dtype=int32)

# stack

In [25]:
x = [1,4]
y = [2,5]
z = [3,6]

tf.stack([x,y,z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [31]:
tf.stack([x,y,z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

# ones and zeros like

In [33]:
x = [[0,1,2], [2,1,0]]
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [35]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)